DATA:
    dataset_name: "CUB_200_2011"
    data_dir: "./data"
    img_size: 128 # can change to lower resolution (must be 2 ** int)
    img_channels: 3
    
METRICS:
    eval_backbone: "InceptionV3_tf"
    ref_dataset: "test"

MODEL:
    z_dim: 100
    c_dim: 256
    channel_base: 32

TRAINING:
    device: 1
    batch_size: 128
    num_workers: 8
    G_lr: 0.0001
    D_lr: 0.0004
    num_epochs: 1000